#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Droid.Resource", IsApplication=true)]

namespace Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::FacebookMonoDroid.Resource.String.library_name = global::Droid.Resource.String.library_name;
			global::HockeyApp.Resource.Color.hockeyapp_background_header = global::Droid.Resource.Color.hockeyapp_background_header;
			global::HockeyApp.Resource.Color.hockeyapp_background_light = global::Droid.Resource.Color.hockeyapp_background_light;
			global::HockeyApp.Resource.Color.hockeyapp_background_white = global::Droid.Resource.Color.hockeyapp_background_white;
			global::HockeyApp.Resource.Color.hockeyapp_button_background = global::Droid.Resource.Color.hockeyapp_button_background;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_pressed = global::Droid.Resource.Color.hockeyapp_button_background_pressed;
			global::HockeyApp.Resource.Color.hockeyapp_button_background_selected = global::Droid.Resource.Color.hockeyapp_button_background_selected;
			global::HockeyApp.Resource.Color.hockeyapp_text_black = global::Droid.Resource.Color.hockeyapp_text_black;
			global::HockeyApp.Resource.Color.hockeyapp_text_light = global::Droid.Resource.Color.hockeyapp_text_light;
			global::HockeyApp.Resource.Color.hockeyapp_text_normal = global::Droid.Resource.Color.hockeyapp_text_normal;
			global::HockeyApp.Resource.Color.hockeyapp_text_white = global::Droid.Resource.Color.hockeyapp_text_white;
			global::HockeyApp.Resource.Drawable.hockeyapp_btn_background = global::Droid.Resource.Drawable.hockeyapp_btn_background;
			global::HockeyApp.Resource.Id.button_add_response = global::Droid.Resource.Id.button_add_response;
			global::HockeyApp.Resource.Id.button_attachment = global::Droid.Resource.Id.button_attachment;
			global::HockeyApp.Resource.Id.button_login = global::Droid.Resource.Id.button_login;
			global::HockeyApp.Resource.Id.button_refresh = global::Droid.Resource.Id.button_refresh;
			global::HockeyApp.Resource.Id.button_send = global::Droid.Resource.Id.button_send;
			global::HockeyApp.Resource.Id.button_update = global::Droid.Resource.Id.button_update;
			global::HockeyApp.Resource.Id.input_email = global::Droid.Resource.Id.input_email;
			global::HockeyApp.Resource.Id.input_message = global::Droid.Resource.Id.input_message;
			global::HockeyApp.Resource.Id.input_name = global::Droid.Resource.Id.input_name;
			global::HockeyApp.Resource.Id.input_password = global::Droid.Resource.Id.input_password;
			global::HockeyApp.Resource.Id.input_subject = global::Droid.Resource.Id.input_subject;
			global::HockeyApp.Resource.Id.label_author = global::Droid.Resource.Id.label_author;
			global::HockeyApp.Resource.Id.label_date = global::Droid.Resource.Id.label_date;
			global::HockeyApp.Resource.Id.label_last_updated = global::Droid.Resource.Id.label_last_updated;
			global::HockeyApp.Resource.Id.label_message = global::Droid.Resource.Id.label_message;
			global::HockeyApp.Resource.Id.label_text = global::Droid.Resource.Id.label_text;
			global::HockeyApp.Resource.Id.label_title = global::Droid.Resource.Id.label_title;
			global::HockeyApp.Resource.Id.label_version = global::Droid.Resource.Id.label_version;
			global::HockeyApp.Resource.Id.list_attachments = global::Droid.Resource.Id.list_attachments;
			global::HockeyApp.Resource.Id.list_feedback_messages = global::Droid.Resource.Id.list_feedback_messages;
			global::HockeyApp.Resource.Id.text_headline = global::Droid.Resource.Id.text_headline;
			global::HockeyApp.Resource.Id.view_header = global::Droid.Resource.Id.view_header;
			global::HockeyApp.Resource.Id.web_update_details = global::Droid.Resource.Id.web_update_details;
			global::HockeyApp.Resource.Id.wrapper_attachments = global::Droid.Resource.Id.wrapper_attachments;
			global::HockeyApp.Resource.Id.wrapper_feedback = global::Droid.Resource.Id.wrapper_feedback;
			global::HockeyApp.Resource.Id.wrapper_feedback_scroll = global::Droid.Resource.Id.wrapper_feedback_scroll;
			global::HockeyApp.Resource.Id.wrapper_messages = global::Droid.Resource.Id.wrapper_messages;
			global::HockeyApp.Resource.Id.wrapper_messages_buttons = global::Droid.Resource.Id.wrapper_messages_buttons;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_expiry_info = global::Droid.Resource.Layout.hockeyapp_activity_expiry_info;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_feedback = global::Droid.Resource.Layout.hockeyapp_activity_feedback;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_login = global::Droid.Resource.Layout.hockeyapp_activity_login;
			global::HockeyApp.Resource.Layout.hockeyapp_activity_update = global::Droid.Resource.Layout.hockeyapp_activity_update;
			global::HockeyApp.Resource.Layout.hockeyapp_fragment_update = global::Droid.Resource.Layout.hockeyapp_fragment_update;
			global::HockeyApp.Resource.Layout.hockeyapp_view_feedback_message = global::Droid.Resource.Layout.hockeyapp_view_feedback_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_app_name_fallback = global::Droid.Resource.String.hockeyapp_crash_dialog_app_name_fallback;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_message = global::Droid.Resource.String.hockeyapp_crash_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_negative_button = global::Droid.Resource.String.hockeyapp_crash_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_neutral_button = global::Droid.Resource.String.hockeyapp_crash_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_positive_button = global::Droid.Resource.String.hockeyapp_crash_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_crash_dialog_title = global::Droid.Resource.String.hockeyapp_crash_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_message = global::Droid.Resource.String.hockeyapp_dialog_error_message;
			global::HockeyApp.Resource.String.hockeyapp_dialog_error_title = global::Droid.Resource.String.hockeyapp_dialog_error_title;
			global::HockeyApp.Resource.String.hockeyapp_dialog_negative_button = global::Droid.Resource.String.hockeyapp_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_dialog_positive_button = global::Droid.Resource.String.hockeyapp_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_message = global::Droid.Resource.String.hockeyapp_download_failed_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_negative_button = global::Droid.Resource.String.hockeyapp_download_failed_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_positive_button = global::Droid.Resource.String.hockeyapp_download_failed_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_download_failed_dialog_title = global::Droid.Resource.String.hockeyapp_download_failed_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_error_no_network_message = global::Droid.Resource.String.hockeyapp_error_no_network_message;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_text = global::Droid.Resource.String.hockeyapp_expiry_info_text;
			global::HockeyApp.Resource.String.hockeyapp_expiry_info_title = global::Droid.Resource.String.hockeyapp_expiry_info_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_file = global::Droid.Resource.String.hockeyapp_feedback_attach_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attach_picture = global::Droid.Resource.String.hockeyapp_feedback_attach_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_button_text = global::Droid.Resource.String.hockeyapp_feedback_attachment_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_error = global::Droid.Resource.String.hockeyapp_feedback_attachment_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_attachment_loading = global::Droid.Resource.String.hockeyapp_feedback_attachment_loading;
			global::HockeyApp.Resource.String.hockeyapp_feedback_email_hint = global::Droid.Resource.String.hockeyapp_feedback_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_text = global::Droid.Resource.String.hockeyapp_feedback_failed_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_failed_title = global::Droid.Resource.String.hockeyapp_feedback_failed_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_fetching_feedback_text = global::Droid.Resource.String.hockeyapp_feedback_fetching_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_generic_error = global::Droid.Resource.String.hockeyapp_feedback_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_last_updated_text = global::Droid.Resource.String.hockeyapp_feedback_last_updated_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_max_attachments_allowed = global::Droid.Resource.String.hockeyapp_feedback_max_attachments_allowed;
			global::HockeyApp.Resource.String.hockeyapp_feedback_message_hint = global::Droid.Resource.String.hockeyapp_feedback_message_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_name_hint = global::Droid.Resource.String.hockeyapp_feedback_name_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_refresh_button_text = global::Droid.Resource.String.hockeyapp_feedback_refresh_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_response_button_text = global::Droid.Resource.String.hockeyapp_feedback_response_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_file = global::Droid.Resource.String.hockeyapp_feedback_select_file;
			global::HockeyApp.Resource.String.hockeyapp_feedback_select_picture = global::Droid.Resource.String.hockeyapp_feedback_select_picture;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_button_text = global::Droid.Resource.String.hockeyapp_feedback_send_button_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_generic_error = global::Droid.Resource.String.hockeyapp_feedback_send_generic_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_send_network_error = global::Droid.Resource.String.hockeyapp_feedback_send_network_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_sending_feedback_text = global::Droid.Resource.String.hockeyapp_feedback_sending_feedback_text;
			global::HockeyApp.Resource.String.hockeyapp_feedback_subject_hint = global::Droid.Resource.String.hockeyapp_feedback_subject_hint;
			global::HockeyApp.Resource.String.hockeyapp_feedback_title = global::Droid.Resource.String.hockeyapp_feedback_title;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_empty = global::Droid.Resource.String.hockeyapp_feedback_validate_email_empty;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_email_error = global::Droid.Resource.String.hockeyapp_feedback_validate_email_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_name_error = global::Droid.Resource.String.hockeyapp_feedback_validate_name_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_subject_error = global::Droid.Resource.String.hockeyapp_feedback_validate_subject_error;
			global::HockeyApp.Resource.String.hockeyapp_feedback_validate_text_error = global::Droid.Resource.String.hockeyapp_feedback_validate_text_error;
			global::HockeyApp.Resource.String.hockeyapp_login_email_hint = global::Droid.Resource.String.hockeyapp_login_email_hint;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text = global::Droid.Resource.String.hockeyapp_login_headline_text;
			global::HockeyApp.Resource.String.hockeyapp_login_headline_text_email_only = global::Droid.Resource.String.hockeyapp_login_headline_text_email_only;
			global::HockeyApp.Resource.String.hockeyapp_login_login_button_text = global::Droid.Resource.String.hockeyapp_login_login_button_text;
			global::HockeyApp.Resource.String.hockeyapp_login_missing_credentials_toast = global::Droid.Resource.String.hockeyapp_login_missing_credentials_toast;
			global::HockeyApp.Resource.String.hockeyapp_login_password_hint = global::Droid.Resource.String.hockeyapp_login_password_hint;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_message = global::Droid.Resource.String.hockeyapp_paint_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_negative_button = global::Droid.Resource.String.hockeyapp_paint_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_neutral_button = global::Droid.Resource.String.hockeyapp_paint_dialog_neutral_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_dialog_positive_button = global::Droid.Resource.String.hockeyapp_paint_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_paint_indicator_toast = global::Droid.Resource.String.hockeyapp_paint_indicator_toast;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_clear = global::Droid.Resource.String.hockeyapp_paint_menu_clear;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_save = global::Droid.Resource.String.hockeyapp_paint_menu_save;
			global::HockeyApp.Resource.String.hockeyapp_paint_menu_undo = global::Droid.Resource.String.hockeyapp_paint_menu_undo;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_negative_button = global::Droid.Resource.String.hockeyapp_permission_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_dialog_positive_button = global::Droid.Resource.String.hockeyapp_permission_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_message = global::Droid.Resource.String.hockeyapp_permission_update_message;
			global::HockeyApp.Resource.String.hockeyapp_permission_update_title = global::Droid.Resource.String.hockeyapp_permission_update_title;
			global::HockeyApp.Resource.String.hockeyapp_update_button = global::Droid.Resource.String.hockeyapp_update_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_message = global::Droid.Resource.String.hockeyapp_update_dialog_message;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_negative_button = global::Droid.Resource.String.hockeyapp_update_dialog_negative_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_positive_button = global::Droid.Resource.String.hockeyapp_update_dialog_positive_button;
			global::HockeyApp.Resource.String.hockeyapp_update_dialog_title = global::Droid.Resource.String.hockeyapp_update_dialog_title;
			global::HockeyApp.Resource.String.hockeyapp_update_mandatory_toast = global::Droid.Resource.String.hockeyapp_update_mandatory_toast;
			global::HockeyApp.Resource.String.hockeyapp_update_version_details_label = global::Droid.Resource.String.hockeyapp_update_version_details_label;
			global::HockeyApp.Resource.String.library_name = global::Droid.Resource.String.library_name;
			global::HockeyApp.Resource.Style.HockeyApp_ButtonStyle = global::Droid.Resource.Style.HockeyApp_ButtonStyle;
			global::HockeyApp.Resource.Style.HockeyApp_EditTextStyle = global::Droid.Resource.Style.HockeyApp_EditTextStyle;
			global::HockeyApp.Resource.Style.HockeyApp_SingleLineInputStyle = global::Droid.Resource.Style.HockeyApp_SingleLineInputStyle;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int hockeyapp_background_header = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int hockeyapp_background_light = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int hockeyapp_background_white = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int hockeyapp_button_background = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int hockeyapp_button_background_pressed = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int hockeyapp_button_background_selected = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int hockeyapp_text_black = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int hockeyapp_text_light = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int hockeyapp_text_normal = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int hockeyapp_text_white = 2131099657;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int androidPhotoMask = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dark_cursor = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int facebook_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int hockeyapp_btn_background = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Icon = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int light_cursor = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int navbarLogo = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int RoundButton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int shadow = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int splash_combo_android = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070088
			public const int access_toolbox_button = 2131165320;
			
			// aapt resource value: 0x7f070089
			public const int access_toolbox_label = 2131165321;
			
			// aapt resource value: 0x7f070037
			public const int activetask = 2131165239;
			
			// aapt resource value: 0x7f07002e
			public const int additionalOptions = 2131165230;
			
			// aapt resource value: 0x7f070064
			public const int address_background = 2131165284;
			
			// aapt resource value: 0x7f070002
			public const int background = 2131165186;
			
			// aapt resource value: 0x7f07006e
			public const int birthdateButton = 2131165294;
			
			// aapt resource value: 0x7f07006d
			public const int birthdateText = 2131165293;
			
			// aapt resource value: 0x7f070004
			public const int bottom_border = 2131165188;
			
			// aapt resource value: 0x7f070006
			public const int button = 2131165190;
			
			// aapt resource value: 0x7f070016
			public const int button_add_response = 2131165206;
			
			// aapt resource value: 0x7f070011
			public const int button_attachment = 2131165201;
			
			// aapt resource value: 0x7f07001b
			public const int button_login = 2131165211;
			
			// aapt resource value: 0x7f070017
			public const int button_refresh = 2131165207;
			
			// aapt resource value: 0x7f070012
			public const int button_send = 2131165202;
			
			// aapt resource value: 0x7f07001f
			public const int button_update = 2131165215;
			
			// aapt resource value: 0x7f070073
			public const int campusButton = 2131165299;
			
			// aapt resource value: 0x7f070072
			public const int campusText = 2131165298;
			
			// aapt resource value: 0x7f070094
			public const int campus_container = 2131165332;
			
			// aapt resource value: 0x7f070071
			public const int campus_middle_border = 2131165297;
			
			// aapt resource value: 0x7f070095
			public const int campus_selection_button = 2131165333;
			
			// aapt resource value: 0x7f070097
			public const int campus_selection_icon = 2131165335;
			
			// aapt resource value: 0x7f070096
			public const int campus_selection_text = 2131165334;
			
			// aapt resource value: 0x7f070032
			public const int cancelButton = 2131165234;
			
			// aapt resource value: 0x7f07004f
			public const int categorySpinner = 2131165263;
			
			// aapt resource value: 0x7f070063
			public const int cellPhoneText = 2131165283;
			
			// aapt resource value: 0x7f070062
			public const int cellphone_background = 2131165282;
			
			// aapt resource value: 0x7f070067
			public const int cityAddressText = 2131165287;
			
			// aapt resource value: 0x7f070068
			public const int city_border = 2131165288;
			
			// aapt resource value: 0x7f07007d
			public const int confirmPasswordText = 2131165309;
			
			// aapt resource value: 0x7f07007c
			public const int confirmPassword_background = 2131165308;
			
			// aapt resource value: 0x7f070001
			public const int connect_primary_list = 2131165185;
			
			// aapt resource value: 0x7f070074
			public const int doneButton = 2131165300;
			
			// aapt resource value: 0x7f070035
			public const int dropShadowView = 2131165237;
			
			// aapt resource value: 0x7f070061
			public const int emailAddressText = 2131165281;
			
			// aapt resource value: 0x7f070060
			public const int email_background = 2131165280;
			
			// aapt resource value: 0x7f070093
			public const int end_seperator = 2131165331;
			
			// aapt resource value: 0x7f070031
			public const int facebookButton = 2131165233;
			
			// aapt resource value: 0x7f070039
			public const int fadeOutView = 2131165241;
			
			// aapt resource value: 0x7f070048
			public const int first_name_background = 2131165256;
			
			// aapt resource value: 0x7f07005c
			public const int firstname_background = 2131165276;
			
			// aapt resource value: 0x7f070033
			public const int fragment_container = 2131165235;
			
			// aapt resource value: 0x7f07003a
			public const int fullscreen = 2131165242;
			
			// aapt resource value: 0x7f070070
			public const int genderButton = 2131165296;
			
			// aapt resource value: 0x7f07006f
			public const int genderText = 2131165295;
			
			// aapt resource value: 0x7f070000
			public const int groupFrame = 2131165184;
			
			// aapt resource value: 0x7f070005
			public const int headerLabel = 2131165189;
			
			// aapt resource value: 0x7f07008c
			public const int icon = 2131165324;
			
			// aapt resource value: 0x7f07000d
			public const int input_email = 2131165197;
			
			// aapt resource value: 0x7f07000f
			public const int input_message = 2131165199;
			
			// aapt resource value: 0x7f07000c
			public const int input_name = 2131165196;
			
			// aapt resource value: 0x7f07001a
			public const int input_password = 2131165210;
			
			// aapt resource value: 0x7f07000e
			public const int input_subject = 2131165198;
			
			// aapt resource value: 0x7f070021
			public const int label_author = 2131165217;
			
			// aapt resource value: 0x7f070022
			public const int label_date = 2131165218;
			
			// aapt resource value: 0x7f070014
			public const int label_last_updated = 2131165204;
			
			// aapt resource value: 0x7f070009
			public const int label_message = 2131165193;
			
			// aapt resource value: 0x7f070023
			public const int label_text = 2131165219;
			
			// aapt resource value: 0x7f07001d
			public const int label_title = 2131165213;
			
			// aapt resource value: 0x7f07001e
			public const int label_version = 2131165214;
			
			// aapt resource value: 0x7f07005f
			public const int lastNameText = 2131165279;
			
			// aapt resource value: 0x7f07004a
			public const int last_name_background = 2131165258;
			
			// aapt resource value: 0x7f07005e
			public const int lastname_background = 2131165278;
			
			// aapt resource value: 0x7f070024
			public const int list_attachments = 2131165220;
			
			// aapt resource value: 0x7f070018
			public const int list_feedback_messages = 2131165208;
			
			// aapt resource value: 0x7f07002b
			public const int loginButton = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int loginResult = 2131165229;
			
			// aapt resource value: 0x7f070026
			public const int login_background = 2131165222;
			
			// aapt resource value: 0x7f070075
			public const int logoutButton = 2131165301;
			
			// aapt resource value: 0x7f070053
			public const int makePublic = 2131165267;
			
			// aapt resource value: 0x7f070054
			public const int makePublicSwitch = 2131165268;
			
			// aapt resource value: 0x7f070029
			public const int middle_border = 2131165225;
			
			// aapt resource value: 0x7f070036
			public const int navbar = 2131165238;
			
			// aapt resource value: 0x7f070025
			public const int navbar_border = 2131165221;
			
			// aapt resource value: 0x7f07003c
			public const int navbar_logo = 2131165244;
			
			// aapt resource value: 0x7f07003b
			public const int navbar_relative_layout = 2131165243;
			
			// aapt resource value: 0x7f070038
			public const int navtoolbar = 2131165240;
			
			// aapt resource value: 0x7f07003e
			public const int news_details_details = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int news_details_launch_url = 2131165247;
			
			// aapt resource value: 0x7f07003d
			public const int news_details_title = 2131165245;
			
			// aapt resource value: 0x7f070040
			public const int news_primary_list = 2131165248;
			
			// aapt resource value: 0x7f07005d
			public const int nickNameText = 2131165277;
			
			// aapt resource value: 0x7f070044
			public const int notes_details_list = 2131165252;
			
			// aapt resource value: 0x7f070045
			public const int notes_primary_activityIndicator = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int notes_primary_list = 2131165254;
			
			// aapt resource value: 0x7f070041
			public const int notes_relative_layout = 2131165249;
			
			// aapt resource value: 0x7f070030
			public const int orTextView = 2131165232;
			
			// aapt resource value: 0x7f070027
			public const int passwordText = 2131165223;
			
			// aapt resource value: 0x7f07002a
			public const int password_background = 2131165226;
			
			// aapt resource value: 0x7f07007b
			public const int password_border = 2131165307;
			
			// aapt resource value: 0x7f07006c
			public const int personal_background = 2131165292;
			
			// aapt resource value: 0x7f070051
			public const int postAnonymous = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int postAnonymousSwitch = 2131165266;
			
			// aapt resource value: 0x7f07004c
			public const int prayerRequest_background = 2131165260;
			
			// aapt resource value: 0x7f070049
			public const int prayer_create_firstNameText = 2131165257;
			
			// aapt resource value: 0x7f07004b
			public const int prayer_create_lastNameText = 2131165259;
			
			// aapt resource value: 0x7f07004d
			public const int prayer_create_requestText = 2131165261;
			
			// aapt resource value: 0x7f070055
			public const int prayer_create_submitButton = 2131165269;
			
			// aapt resource value: 0x7f07005a
			public const int prayer_primary_activityIndicator = 2131165274;
			
			// aapt resource value: 0x7f070086
			public const int profile_name = 2131165318;
			
			// aapt resource value: 0x7f070084
			public const int profile_name_linearlayout = 2131165316;
			
			// aapt resource value: 0x7f070085
			public const int profile_prefix = 2131165317;
			
			// aapt resource value: 0x7f070043
			public const int progressBar = 2131165251;
			
			// aapt resource value: 0x7f07007e
			public const int progressBarBlocker = 2131165310;
			
			// aapt resource value: 0x7f070042
			public const int refreshButton = 2131165250;
			
			// aapt resource value: 0x7f07002f
			public const int registerButton = 2131165231;
			
			// aapt resource value: 0x7f070047
			public const int relative_background = 2131165255;
			
			// aapt resource value: 0x7f07005b
			public const int relative_layout = 2131165275;
			
			// aapt resource value: 0x7f070058
			public const int resultSymbol = 2131165272;
			
			// aapt resource value: 0x7f07002c
			public const int result_background = 2131165228;
			
			// aapt resource value: 0x7f070059
			public const int retryButton = 2131165273;
			
			// aapt resource value: 0x7f070076
			public const int scroll_background = 2131165302;
			
			// aapt resource value: 0x7f070077
			public const int scroll_linear_background = 2131165303;
			
			// aapt resource value: 0x7f070007
			public const int scroll_view = 2131165191;
			
			// aapt resource value: 0x7f07008d
			public const int seperator = 2131165325;
			
			// aapt resource value: 0x7f07004e
			public const int spinner_background = 2131165262;
			
			// aapt resource value: 0x7f070034
			public const int springboard = 2131165236;
			
			// aapt resource value: 0x7f070092
			public const int springboard_about_frame = 2131165330;
			
			// aapt resource value: 0x7f070090
			public const int springboard_connect_frame = 2131165328;
			
			// aapt resource value: 0x7f07008a
			public const int springboard_container = 2131165322;
			
			// aapt resource value: 0x7f07008f
			public const int springboard_give_frame = 2131165327;
			
			// aapt resource value: 0x7f070083
			public const int springboard_login_button = 2131165315;
			
			// aapt resource value: 0x7f07008b
			public const int springboard_news_frame = 2131165323;
			
			// aapt resource value: 0x7f07008e
			public const int springboard_notes_frame = 2131165326;
			
			// aapt resource value: 0x7f070091
			public const int springboard_prayer_frame = 2131165329;
			
			// aapt resource value: 0x7f070082
			public const int springboard_profile_image = 2131165314;
			
			// aapt resource value: 0x7f070080
			public const int springboard_profile_image_container = 2131165312;
			
			// aapt resource value: 0x7f070081
			public const int springboard_profile_image_layout = 2131165313;
			
			// aapt resource value: 0x7f07007f
			public const int springboard_relative_layout = 2131165311;
			
			// aapt resource value: 0x7f070069
			public const int stateAddressText = 2131165289;
			
			// aapt resource value: 0x7f07006a
			public const int state_border = 2131165290;
			
			// aapt resource value: 0x7f070056
			public const int status_background = 2131165270;
			
			// aapt resource value: 0x7f070065
			public const int streetAddressText = 2131165285;
			
			// aapt resource value: 0x7f070066
			public const int street_border = 2131165286;
			
			// aapt resource value: 0x7f070050
			public const int switch_background = 2131165264;
			
			// aapt resource value: 0x7f070057
			public const int text = 2131165271;
			
			// aapt resource value: 0x7f070019
			public const int text_headline = 2131165209;
			
			// aapt resource value: 0x7f070003
			public const int top_border = 2131165187;
			
			// aapt resource value: 0x7f070079
			public const int userNameText = 2131165305;
			
			// aapt resource value: 0x7f070028
			public const int usernameText = 2131165224;
			
			// aapt resource value: 0x7f070078
			public const int username_background = 2131165304;
			
			// aapt resource value: 0x7f07007a
			public const int username_border = 2131165306;
			
			// aapt resource value: 0x7f070008
			public const int view_background = 2131165192;
			
			// aapt resource value: 0x7f07001c
			public const int view_header = 2131165212;
			
			// aapt resource value: 0x7f070087
			public const int view_profile = 2131165319;
			
			// aapt resource value: 0x7f070020
			public const int web_update_details = 2131165216;
			
			// aapt resource value: 0x7f070010
			public const int wrapper_attachments = 2131165200;
			
			// aapt resource value: 0x7f07000b
			public const int wrapper_feedback = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int wrapper_feedback_scroll = 2131165194;
			
			// aapt resource value: 0x7f070013
			public const int wrapper_messages = 2131165203;
			
			// aapt resource value: 0x7f070015
			public const int wrapper_messages_buttons = 2131165205;
			
			// aapt resource value: 0x7f07006b
			public const int zipAddressText = 2131165291;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BiblePassage = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Connect_GroupFinder = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Connect_Primary = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int DatePicker = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Give_Primary = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int GroupInfo = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int hockeyapp_activity_expiry_info = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int hockeyapp_activity_feedback = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int hockeyapp_activity_login = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int hockeyapp_activity_update = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int hockeyapp_fragment_update = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int hockeyapp_view_feedback_message = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int ImageCrop = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int JoinGroup = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int Login = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int Main = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int navbar = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int News_Details = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int News_Primary = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int Notes = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int Notes_Details = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int Notes_Primary = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int OOBEView = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int Prayer_Create = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int Prayer_Post = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int Prayer_Primary = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int Profile = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int Register = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int Splash = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int Springboard = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int TaskWebView = 2130903070;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040049
			public const int app_name = 2130968649;
			
			// aapt resource value: 0x7f040048
			public const int hello = 2130968648;
			
			// aapt resource value: 0x7f040001
			public const int hockeyapp_crash_dialog_app_name_fallback = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int hockeyapp_crash_dialog_message = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int hockeyapp_crash_dialog_negative_button = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int hockeyapp_crash_dialog_neutral_button = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int hockeyapp_crash_dialog_positive_button = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int hockeyapp_crash_dialog_title = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int hockeyapp_dialog_error_message = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int hockeyapp_dialog_error_title = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int hockeyapp_dialog_negative_button = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int hockeyapp_dialog_positive_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int hockeyapp_download_failed_dialog_message = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int hockeyapp_download_failed_dialog_negative_button = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int hockeyapp_download_failed_dialog_positive_button = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int hockeyapp_download_failed_dialog_title = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int hockeyapp_error_no_network_message = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int hockeyapp_expiry_info_text = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int hockeyapp_expiry_info_title = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int hockeyapp_feedback_attach_file = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int hockeyapp_feedback_attach_picture = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int hockeyapp_feedback_attachment_button_text = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int hockeyapp_feedback_attachment_error = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int hockeyapp_feedback_attachment_loading = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int hockeyapp_feedback_email_hint = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int hockeyapp_feedback_failed_text = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int hockeyapp_feedback_failed_title = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int hockeyapp_feedback_fetching_feedback_text = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int hockeyapp_feedback_generic_error = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int hockeyapp_feedback_last_updated_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int hockeyapp_feedback_max_attachments_allowed = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int hockeyapp_feedback_message_hint = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int hockeyapp_feedback_name_hint = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int hockeyapp_feedback_refresh_button_text = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int hockeyapp_feedback_response_button_text = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int hockeyapp_feedback_select_file = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int hockeyapp_feedback_select_picture = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int hockeyapp_feedback_send_button_text = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int hockeyapp_feedback_send_generic_error = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int hockeyapp_feedback_send_network_error = 2130968614;
			
			// aapt resource value: 0x7f040027
			public const int hockeyapp_feedback_sending_feedback_text = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int hockeyapp_feedback_subject_hint = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int hockeyapp_feedback_title = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int hockeyapp_feedback_validate_email_empty = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int hockeyapp_feedback_validate_email_error = 2130968619;
			
			// aapt resource value: 0x7f04002c
			public const int hockeyapp_feedback_validate_name_error = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int hockeyapp_feedback_validate_subject_error = 2130968621;
			
			// aapt resource value: 0x7f04002e
			public const int hockeyapp_feedback_validate_text_error = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int hockeyapp_login_email_hint = 2130968623;
			
			// aapt resource value: 0x7f040030
			public const int hockeyapp_login_headline_text = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int hockeyapp_login_headline_text_email_only = 2130968625;
			
			// aapt resource value: 0x7f040032
			public const int hockeyapp_login_login_button_text = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int hockeyapp_login_missing_credentials_toast = 2130968627;
			
			// aapt resource value: 0x7f040034
			public const int hockeyapp_login_password_hint = 2130968628;
			
			// aapt resource value: 0x7f040035
			public const int hockeyapp_paint_dialog_message = 2130968629;
			
			// aapt resource value: 0x7f040036
			public const int hockeyapp_paint_dialog_negative_button = 2130968630;
			
			// aapt resource value: 0x7f040037
			public const int hockeyapp_paint_dialog_neutral_button = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int hockeyapp_paint_dialog_positive_button = 2130968632;
			
			// aapt resource value: 0x7f040039
			public const int hockeyapp_paint_indicator_toast = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int hockeyapp_paint_menu_clear = 2130968634;
			
			// aapt resource value: 0x7f04003b
			public const int hockeyapp_paint_menu_save = 2130968635;
			
			// aapt resource value: 0x7f04003c
			public const int hockeyapp_paint_menu_undo = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int hockeyapp_permission_dialog_negative_button = 2130968637;
			
			// aapt resource value: 0x7f04003e
			public const int hockeyapp_permission_dialog_positive_button = 2130968638;
			
			// aapt resource value: 0x7f04003f
			public const int hockeyapp_permission_update_message = 2130968639;
			
			// aapt resource value: 0x7f040040
			public const int hockeyapp_permission_update_title = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int hockeyapp_update_button = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int hockeyapp_update_dialog_message = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int hockeyapp_update_dialog_negative_button = 2130968643;
			
			// aapt resource value: 0x7f040044
			public const int hockeyapp_update_dialog_positive_button = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int hockeyapp_update_dialog_title = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int hockeyapp_update_mandatory_toast = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int hockeyapp_update_version_details_label = 2130968647;
			
			// aapt resource value: 0x7f040000
			public const int library_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int HockeyApp_ButtonStyle = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int HockeyApp_EditTextStyle = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int HockeyApp_SingleLineInputStyle = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int MobileTheme = 2131034115;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
